### ISSUE TITLE
Can't decrease Break length in main timer.

### ISSUE THREAD

**Issue by sunil-sangwan** [MayankPratap/pomodoro-timer#1]
When I try to increase or decrease in Session time then in timer it shows its effect but in same thing want to happen with Break length, but it is not working.

**Comment by MayankPratap** [comment]
That was intentional. This is because first session will happen and then you will take a break . If you increase or decrease break time , you will be able to see its effect only when one session is complete. 

Try changing break length to 3 min and session length to 1 min and then click on timer (elliptical or circular portion) . After 1 min , you will see break starting from 3 min .

Please close the issue if satisfied .

**Comment by sunil-sangwan** [comment]
Assume I want to change my break time from 5 to 10 min. in break session then it is not able to do so.

**Comment by MayankPratap** [comment]
I have fixed some bugs . Now its working like this :- 
1) If session is running, you cant change break length or session length. You will have to pause the timer (To pause the timer, click on timer again)  and then you can change session length and/or break length. You will observe changes in break length when break time starts. You will observe changes in session length immediately when you resume the timer(To resume the timer click on it).

2) If break is running, you can neither change session length or break length . You will have to pause the timer (To pause the timer click on timer again)  and then you can change session length and/or break length. You can observe changes in break time immediately after you resume the timer . You can observe the change in session length once break is over and session starts.

Please comment if you are facing any issue.

**Comment by sunil-sangwan** [comment]
Cool :+1:
